-- MySQL Script generated by MySQL Workbench
-- 05/24/18 12:25:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `catagory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catagory` ;

CREATE TABLE IF NOT EXISTS `catagory` (
  `cata_id` INT NOT NULL AUTO_INCREMENT COMMENT '总分类id',
  `cata_name` VARCHAR(15) NULL COMMENT '分类名',
  PRIMARY KEY (`cata_id`))
ENGINE = InnoDB
COMMENT = '总分类';


-- -----------------------------------------------------
-- Table `subcata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subcata` ;

CREATE TABLE IF NOT EXISTS `subcata` (
  `sub_id` INT NOT NULL AUTO_INCREMENT COMMENT '子分类id',
  `sub_name` VARCHAR(15) NULL COMMENT '子分类名',
  `cata_id` INT NULL COMMENT '总分类id',
  PRIMARY KEY (`sub_id`))
ENGINE = InnoDB
COMMENT = '子分类';


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `user_name` VARCHAR(31) NULL COMMENT '用户名',
  `user_password` VARCHAR(63) NULL COMMENT '密码',
  `phone` VARCHAR(15) NULL COMMENT '手机号',
  `address` VARCHAR(127) NULL COMMENT '地址',
  `code` VARCHAR(15) NULL COMMENT '邮编',
  `money` INT NULL COMMENT '余额',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manager` ;

CREATE TABLE IF NOT EXISTS `manager` (
  `mana_id` INT NOT NULL AUTO_INCREMENT COMMENT '商品管理员id',
  `mana_name` VARCHAR(31) NULL COMMENT '名字',
  `mana_password` VARCHAR(63) NULL COMMENT '密码',
  PRIMARY KEY (`mana_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transportation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transportation` ;

CREATE TABLE IF NOT EXISTS `transportation` (
  `tran_id` VARCHAR(31) NOT NULL COMMENT '快递编号',
  `trer_id` INT NULL COMMENT '快递员id',
  `cart_id` INT NULL COMMENT '购物车id',
  PRIMARY KEY (`tran_id`))
ENGINE = InnoDB
COMMENT = '快递';


-- -----------------------------------------------------
-- Table `transporter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transporter` ;

CREATE TABLE IF NOT EXISTS `transporter` (
  `trer_id` INT NOT NULL AUTO_INCREMENT COMMENT '快递员id',
  `trer_name` VARCHAR(31) NULL COMMENT '快递员名称',
  `trer_password` VARCHAR(63) NULL COMMENT '密码',
  PRIMARY KEY (`trer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tran_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tran_info` ;

CREATE TABLE IF NOT EXISTS `tran_info` (
  `tran_info_id` INT NOT NULL AUTO_INCREMENT COMMENT '快递信息id',
  `tran_id` VARCHAR(31) NULL COMMENT '快递编号',
  `tran_info_context` VARCHAR(127) NULL COMMENT '快递详情',
  PRIMARY KEY (`tran_info_id`))
ENGINE = InnoDB
COMMENT = '快递信息';


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `pro_id` INT NOT NULL AUTO_INCREMENT COMMENT '商品id',
  `pro_name` VARCHAR(63) NULL COMMENT '商品名称',
  `pro_price` INT NULL COMMENT '商品价格',
  `pro_stack` INT NULL COMMENT '商品库存',
  `pro_size` VARCHAR(31) NULL COMMENT '商品规格',
  `pro_desc` VARCHAR(255) NULL COMMENT '商品描述',
  `sub_id` INT NULL COMMENT '子分类id',
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB
COMMENT = '商品';


-- -----------------------------------------------------
-- Table `shopcart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopcart` ;

CREATE TABLE IF NOT EXISTS `shopcart` (
  `cart_id` INT NOT NULL COMMENT '购物车id',
  `user_id` INT NULL COMMENT '用户id',
  `pro_id` INT NULL COMMENT '商品id',
  `buy_num` INT NULL COMMENT '购买数量',
  `cart_state` INT NULL COMMENT '购买状态:0未购买，1购买',
  PRIMARY KEY (`cart_id`))
ENGINE = InnoDB
COMMENT = '购物车';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
